version: "2"
services:
  riemann-dash:
    container_name: "riemann-dash"
    build: .
    ports:
     - "4567:4567"
  riemann:
    container_name: "riemann"
    image: "mnuessler/riemann"
    ports:
    - "5555:5555"
    - "5556:5556"
    environment:
    - RIEMANN_VERSION=0.2.12
    volumes:
     - ./src/riemann_etc:/etc/riemann/conf.d
  influxdb:
    container_name: "influxdb"
    image: "tutum/influxdb"
    ports:
    - "8083:8083"
    - "8086:8086"
    environment:
    - ADMIN_USER=root
    - INFLUXDB_INIT_PWD=root
    - PRE_CREATE_DB=riemann
  grafana:
    container_name: "grafana"
    image: "grafana/grafana"
    ports:
    - "3000:3000"
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=admin
  smtp:
    container_name: "smtp"
    image: "namshi/smtp"
